### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by burner1024** [NearInfinityBrowser/NearInfinity#80] opened 2016-05-09 16:30 UTC
In my environment, for some reason no settings are saved between restarts. Every time I select chitin.key, change indent, look and feel, etc. Upon a restart, it's not preserved.
I tried 1.36-20160214 and 20160502 by Argent77. Mac OS 10.10.5

**Comment by Argent77** [comment] 2016-05-09 20:19
I don't have much experience with Mac OS X, so I can only be of limited help.

Try starting Near Infinity from the terminal. Change into the directory where NI is located and execute `java -jar NearInfinity.jar`. Does the console show any error messages after starting NI that way?

Afaik, the preferences are stored in the path `~/Library/Preferences` on OS X. Try th following:
- Delete all files starting with `infinity.*` or `org.infinity.*`. 
- Rename Java's main preferences file `com.apple.java.util.prefs.plist` -> `com.apple.java.util.prefs.plist-bak` (or move it into another folder)

Then start NI again and make your changes. Quit and restart NI again. Do the changes stick?

(*Note: You should probably restore `com.apple.java.util.prefs.plist` afterwards if you have more Java applications which store their settings locally or you have to recreate their respective settings.*)

**Comment by AstroBryGuy** [comment] 2016-05-10 01:42
Note - on OSX, `/usr/bin/java` is a stub that references the `JAVA_HOME` environment variable, but it only works if you have the JDK installed. If you don't have the JDK installed, `/usr/bin/java` may point to the ancient Apple-supplied Java 1.6. NI needs at least Java 1.8. If you have the 1.8 JRE installed, it can be found at 

`/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java`

So, argent77's command above should be `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -jar NearInfinity.jar`

**Comment by burner1024** [comment] 2016-05-10 03:02
I am starting it from terminal. There are no errors.

No, the changes don't stick after deleting plist files.

```
java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

**Comment by Argent77** [comment] 2016-05-10 10:13
Try the second option from my previous comment again (i.e. remove/rename relevant `*.plist` files) and restart the system before starting NI. Apparently the Java VM continues to use cached settings until you restart the system.

Another possible culprit is described [in this topic](https://discussions.apple.com/thread/4124439?tstart=0). This issue is mainly about Java's own preferences, but it might also affect settings from Java applications. There may be other applications interfering with Java as well.

**Comment by burner1024** [comment] 2016-05-10 11:31
No, reboot didn't help. I don't have any cache cleaners installed, either.

**Comment by Argent77** [comment] 2017-08-30 08:50
Could not reproduce. Closing issue.

**Comment by burner1024** [comment] 2017-08-31 15:36
Did some testing with NearInfinity-20170809, and I think I've found the problem. Settings don't get saved when "command-Q" is used to exit the program. When quit option is selected from menu, they are persevered normally.

**Comment by Argent77** [comment] 2017-08-31 15:57
That's useful info.

Could you try out the following workaround?

Insert the following code to `src/org/infinity/NearInfinity.java` around line 116:
```
  static {
    // XXX: Workaround to trigger standard window closing callback on OSX when 
    //      using command-Q shortcut
    System.setProperty("apple.eawt.quitStrategy", "CLOSE_ALL_WINDOWS");
  }
```
and build NearInfinity.jar.

**Comment by burner1024** [comment] 2017-08-31 16:22
No, didn't help.

**Comment by Argent77** [comment] 2017-08-31 16:55
Let's try a different strategy.

Please add the following method to the NearInfinity class (`src/org/infinity/NearInfinity.java`):
```
  @SuppressWarnings({ "unchecked", "rawtypes" })
  private void enableOSXQuitStrategy()
  {
    try {
      Class application = Class.forName("com.apple.eawt.Application");
      Method getApplication = application.getMethod("getApplication");
      Object instance = getApplication.invoke(application);
      Class strategy = Class.forName("com.apple.eawt.QuitStrategy");
      Enum closeAllWindows = Enum.valueOf(strategy, "CLOSE_ALL_WINDOWS");
      Method method = application.getMethod("setQuitStrategy", strategy);
      method.invoke(instance, closeAllWindows);
    } catch (ClassNotFoundException |
             NoSuchMethodException |
             SecurityException |
             IllegalAccessException |
             IllegalArgumentException |
             InvocationTargetException e) {
      e.printStackTrace();
    }
  }
```

and this code to the end of the constructor (same class):
```
    if (System.getProperty("os.name").startsWith("Mac OS X")) {
      enableOSXQuitStrategy();
    }
```

**Comment by burner1024** [comment] 2017-09-01 14:19
Getting some errors on compilation. Maybe you could provide a diff? I'm not well versed in Java.

**Comment by Argent77** [comment] 2017-09-01 14:30
Here you go:
```diff
diff --git a/src/org/infinity/NearInfinity.java b/src/org/infinity/NearInfinity.java
index a5b43fd..ffecf86 100644
--- a/src/org/infinity/NearInfinity.java
+++ b/src/org/infinity/NearInfinity.java
@@ -26,6 +26,8 @@
 import java.io.File;
 import java.io.OutputStream;
 import java.io.PrintStream;
+import java.lang.reflect.InvocationTargetException;
+import java.lang.reflect.Method;
 import java.nio.file.Files;
 import java.nio.file.Path;
 import java.util.ArrayList;
@@ -449,6 +451,10 @@
     setLocation(prefs.getInt(WINDOW_POSX, centerX), prefs.getInt(WINDOW_POSY, centerY));
     setVisible(true);
     setExtendedState(prefs.getInt(WINDOW_STATE, NORMAL));
+
+    if (System.getProperty("os.name").startsWith("Mac OS X")) {
+      enableOSXQuitStrategy();
+    }
 
     tableColumnWidth[0] = Math.max(15, prefs.getInt(TABLE_WIDTH_ATTR, 300));
     tableColumnWidth[1] = 0;
@@ -944,6 +950,26 @@
     }
   }
 
+  @SuppressWarnings({ "unchecked", "rawtypes" })
+  private void enableOSXQuitStrategy()
+  {
+    try {
+      Class application = Class.forName("com.apple.eawt.Application");
+      Method getApplication = application.getMethod("getApplication");
+      Object instance = getApplication.invoke(application);
+      Class strategy = Class.forName("com.apple.eawt.QuitStrategy");
+      Enum closeAllWindows = Enum.valueOf(strategy, "CLOSE_ALL_WINDOWS");
+      Method method = application.getMethod("setQuitStrategy", strategy);
+      method.invoke(instance, closeAllWindows);
+    } catch (ClassNotFoundException |
+             NoSuchMethodException |
+             SecurityException |
+             IllegalAccessException |
+             IllegalArgumentException |
+             InvocationTargetException e) {
+      e.printStackTrace();
+    }
+  }
 
 // -------------------------- INNER CLASSES --------------------------
 
```

It's based on current devel branch of https://github.com/Argent77/NearInfinity/ .

**Comment by burner1024** [comment] 2017-09-01 19:00
Yes, that did it! Thanks you.

**Comment by Argent77** [comment] 2017-09-01 19:48
[Fixed](https://github.com/Argent77/NearInfinity/commit/cf46163d80ea29a4efcef44f0072e066ec11134f).

**Closed by Argent77** 2017-09-01 19:48 UTC
