### ISSUE TITLE
Hangs when viewing actors in IWD2 Prologue Auto-save

### ISSUE THREAD

**Issue by asik** [NearInfinityBrowser/NearInfinity#177] opened 2024-04-06 07:48 UTC
[000000000-Autosave - Prologue.zip](https://github.com/NearInfinityBrowser/NearInfinity/files/14892872/000000000-Autosave.-.Prologue.zip)

Repro:

 - Start an Icewind Dale 2 game or use the linked save game
 - Open NI
 - Open Mpsave/00000000-Autosave-Prologue/ICEWIND2.SAV
 - Decompress AR1000.ARE
 - View/Edit AR1000.ARE
 - View/Edit any of the actors

Observed:
 - NI starts consuming 100% of CPU. Eventually it stops but fails to open the actor.

Remarks:
 - Can repro with different saves but not all.
 
![image](https://github.com/NearInfinityBrowser/NearInfinity/assets/1631157/6b9c811d-ca96-4337-b575-b1361037f5a0)

Windows 10
Version 2.4-20231231

**Comment by Argent77** [comment] 2024-04-06 08:12
I can't reproduce it with my own saves. But your attached save produces the same effect on my system. It looks like NI attempts to continuously allocate memory and fails eventually when no more memory is available. I'll look into it.

**Comment by asik** [comment] 2024-04-06 08:14
The earliest version I repro with is [Version 2.4-20230729](https://github.com/Argent77/NearInfinity/releases/tag/v2.4-20230729).

**Comment by Argent77** [comment] 2024-04-06 17:33
Issue should be fixed now. It can be tested in the [Nightly release](https://github.com/Argent77/NearInfinity/releases/tag/nightly).

**Comment by Argent77** [comment] 2024-04-06 20:02
Commit 3f2507d should handle both valid and malformed resources in saved games without locking the app.

As mentioned before, the [nightly release](https://github.com/Argent77/NearInfinity/releases/tag/nightly) can be used to test the latest changes.

**Comment by asik** [comment] 2024-04-07 01:29
> Issue should be fixed now. It can be tested in the [Nightly release](https://github.com/Argent77/NearInfinity/releases/tag/nightly).
> 
> **Edit:** After further testing it looks like you've stumbled upon a bug in IWD2 itself which creates malformed files in the save if a certain predefined party is used. You can see the result in the game by opening the biography of the first party member which should be incomplete.
> 
> I'll see if I can modify the fix to work on both correct and malformed saves.

That's very insightful, thank you! Looks like the latest nightly fixes it indeed.

**Closed** 2024-04-07 12:36 UTC
Labels: bug
