### ISSUE TITLE
Freeze if a I have an unsaved asset and attempt to switch to a different game without finishing or cancelling the edit

### ISSUE THREAD

**Issue by szaumoor** [NearInfinityBrowser/NearInfinity#192] opened 2024-12-08 13:22 UTC
Steps to reproduce in my system (Windows 10, 64 bits):

1. Open NearInfinity for BGEE
2. Open MINSC.CRE
3. Duplicate an entry in the list of effects: Modify Proficiencies (opcode 233)
4. Click on Game -> Recently opened Games -> BG2EE
5. The warning window appears, sometimes without visible content, sometimes with. This warning window cannot be interacted with in any way, so the program is effectively frozen and must be killed.

Using the nightly build, I don't see any output other than an INFO debug log about opening the game resources when I first load NearInfinity, and another one when I try to switch (when the freeze happens). Maybe it's trying to load the game irrespective of the warning window?

Other system information:
![image](https://github.com/user-attachments/assets/501bd690-2306-4581-8c13-9543ae8d5962)

Let me know if I can help further.

**Comment by Argent77** [comment] 2024-12-08 13:26
Thanks.

I can reproduce this issue with these specific repro steps. I'll look into it.

**Comment by Argent77** [comment] 2024-12-08 21:06
It looks like the real cause for this and other anomalies with the "Save resource" confirmation dialog is ancient. I could trace it back to early 2016 releases. It may take a while to sort it all out.

**Comment by Argent77** [comment] 2024-12-09 12:57
> It looks like the real cause for this and other anomalies with the "Save resource" confirmation dialog is ancient. I could trace it back to early 2016 releases. It may take a while to sort it all out.

Looks like these other issues are unrelated to the reported issues.

Could you test if the locks still happen with the latest [nightly release](https://github.com/Argent77/NearInfinity/releases/tag/nightly)?

**Comment by szaumoor** [comment] 2024-12-09 16:24
> Looks like these other issues are unrelated to the reported issue.
> 
> Could you test if the locks still happen with the latest [nightly release](https://github.com/Argent77/NearInfinity/releases/tag/nightly)?

It no longer happens, awesome! Now it patiently waits for confirmation on the unsaved asset, and doesn't freeze.

**Comment by Argent77** [comment] 2024-12-09 16:40
Good to know.

> Now it patiently waits for confirmation on the unsaved asset, and doesn't freeze.

Yeah, that particular issue dates back to early 2016 releases and can probably only be fixed by a fundamental design change.

**Closed by Argent77** 2024-12-09 16:40 UTC
